### ISSUE TITLE
Add support for C# 8.0 features

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/core#1049]
New language features: (See [Building C# 8.0](https://devblogs.microsoft.com/dotnet/building-c-8-0/))

- [x] Nullable reference types
  - [x] Test added 
- [ ] `IAsyncDisposable` and `using` - TODO #1222
  - [x] Test added 
- [ ] `IAsyncEnumerable` and `await foreach` - TODO #1222
  - [x] Test added 
- [ ] `Index` and `Range` types - TODO #1223
  - [x] Test added 
- [ ] Default implementations of interface members - TODO #1224
  - [x] Test added 
- [x] Recursive patterns
  - [x] Test added 
- [x] Switch expressions
  - [x] Test added

**Comment by Jand42** [comment]
As of WebSharper 6, not yet supported features are moved out to separate tickets, see linked above. Closing this.
