### ISSUE TITLE
Add support for C# 10.0 features

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/core#1219]
New language features: (See [What’s new in C# 10](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10))

- [x] Update to `Microsoft.CodeAnalysis.CSharp 4.0.1`
- [ ] Record structs - TODO #1237
  - [x] Test added 
- [x] Improvements of structure types
  - [x] Test added 
- [ ] Interpolated string handler - TODO #1238
  - [ ] Test added 
- [x] Global using directives
  - [x] Test added
- [x] File-scoped namespace declaration
  - [x] Test added
- [x] Extended property patterns
  - [x] Test added
- [x] Lambda expression improvements
  - [x] Test added
- [x] Constant interpolated strings
  - [x] Test added
- [x] Record types can seal ToString
  - [x] Test added
* Support for `AsyncMethodBuilder`
  * Too low-level feature, based on the state machine transformations of `async` functions. There are other `async` features, that would be more useful: #700, #1222, #542
- [ ] Support for CallerArgumentExpression - TODO #1239
  - [x] Test added

**Comment by Jand42** [comment]
As of WebSharper 6, not yet supported features are moved out to separate tickets, see linked above. Closing this.
